### ISSUE TITLE
remove snidflat.pro from repo, but add link to Stephane's webpage

### ISSUE THREAD

**Issue by mmoJazz** [nyusngroup/SESNspectraLib#10]
According to the email below from Stephane, he doesn't want us to release snidflat.pro, but to link to his webpage.

On 6/24/16 2:11 AM, Stephane Blondin wrote:
Hi Maryam,

Thanks for your note. Of course I'm generally favourable in publishing
code whenever possible. SNID is currently part of the Astrophysics
Source Code Library under ID ascl:1107.001 (see
http://ascl.net/phpBB3/viewtopic.php?t=24326), but the distribution does
not include the snidflat.pro and associated IDL routines.

I'd rather be the one who publishes these routines. To not further delay
the publication of your paper I have posted the snidflat.pro etc. on my
SNID webpage, so you can simply link to there:
https://people.lam.fr/blondin.stephane/software/snid/index.html (see
Download section). At some point I'll think about making these available
via github etc., but this won't happen in the immediate future (I'm
leaving on vacation next week).

Note that flattening spectra "a la SNID" can also be achieved using the
logwave program, which _is_ part of the public SNID distribution.

Last, I did not write the binspec.pro routine (at least I don't think
so!). I can't seem to find who the original author is...

Cheers,

Stephane

**Comment by yoyo1989** [comment]
Done.
