### ISSUE TITLE
Ic_conv_Icbl_MCMC.py run on smoothed or non-smoothed spectrum

### ISSUE THREAD

**Issue by mmoJazz** [nyusngroup/SESNspectraLib#30]
I cut out this question from my other longer thread, so that it's dealt with separately:

> Question: will the fit be performed on the filtered/smoothed version of
> the 10qts file or the non-filtered/non-smooothed ? I think we had agreed
> that it would be on the non-smoothed! So in that case let's remove the
> smoothed spectrum in the input!

**Comment by yoyo1989** [comment]
yes, it makes sense. I'll do it!

**Comment by yoyo1989** [comment]
yes, the code run on non-smoothed spectrum.

**Comment by yoyo1989** [comment]
I realize that the smoothed spectrum is still useful. I use the smoothed spectrum to find local maxima around the absorption feature. The region between two local maxima is the initial fitting region.
