### ISSUE TITLE
powerlaw_fit.pro and linear_fit.pro in SNspecFFTsmooth.pro

### ISSUE THREAD

**Issue by mmoJazz** [nyusngroup/SESNspectraLib#31]
Yuqian, which powerlaw_fit.pro do you use? It's not in any of my  libraries (that you presumably had copied over).

Is it this one? This is my friend Erik Rosolowsky's library:
https://people.ok.ubc.ca/erosolo/idl/lib/powerlaw_fit.pro

I seem to have linear_fit.pro in my IDL/fit folder, as well as exponential_fit - which I had gotten from Erik originally!

So for both the 2 fit codes you are using (linear_fit.pro and powerlaw_fit.pro)  you need to mention those, including links since those are not in the standard IDL libraries.

**Comment by yoyo1989** [comment]
Yes, both powerlaw_fit.pro and linear_fit.pro are from Erik Rosolowsky's library. I've added them as dependent code in the SNspecFFTsmooth.pro.
