### ISSUE TITLE
comments welcome

### ISSUE THREAD

**Issue by yoyo1989** [nyusngroup/SESNspectraLib#4]
I've done with this repository. Please have a look and list comments under this issue or open new issues. Once I've implemented the comments, I'll close issues. Thanks!

**Comment by fedhere** [comment]
Hi @orgraur, can you take a quick look at the repo and tell us if it looks good to you?, ideally download and test the code, since you run  a linux box and we all have macs

**Comment by fedhere** [comment]
@orgraur 
please run the code and remind to report which version of python you use to run it

thanks!

**Comment by fedhere** [comment]
I am copying and pasting the conversation I am having with Or in a separate issue

**Comment by fedhere** [comment]
@orgraur thanks for running the code. if you have any more comments please let us know, if not please close the isse, thanks again!

**Comment by fedhere** [comment]
@orgraur  i am closing this, i assume you are done commenting.
