### ISSUE TITLE
youd code does not save a fit figure?

### ISSUE THREAD

**Issue by fedhere** [nyusngroup/SESNspectraLib#6]
your code Ic_conv does not generate a figure like Fig 10 in Modjaz 15? I think it should. Either as a default or at least upon request

**Comment by fedhere** [comment]
nevermind, it does! however it saves everything in the same multi page PDF. fit diagnostics and fit results should be saved separately. I am changing it to save 2 output files, one for th fit, one for the triangle plot, and to NOT to save the panel w the walkers (at least not as a default)

**Comment by fedhere** [comment]
i separated the pdf outputs. check that you are ok with this.

**Comment by yoyo1989** [comment]
Thanks Fed! I'm OK with this. I also added some legend and changed the unit from '\AA' to the symbol angstrom.
