### ISSUE TITLE
added bibtex to readme

### ISSUE THREAD

**Issue by fedhere** [nyusngroup/SESNspectraLib#7]
this may be a good idea for citations. check that they are what you want

**Comment by yoyo1989** [comment]
How about changing the 'year = 2015' to 'year = 2016'?

**Comment by fedhere** [comment]
sure!

On Sun, Jul 3, 2016 at 4:09 PM, Yuqian Liu notifications@github.com wrote:

> How about changing the 'year = 2015' to 'year = 2016'?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/nyusngroup/SESNspectraLib/issues/7#issuecomment-230172643,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABnkhhoZeMgNczpnK_tIuEBuug1f5HAKks5qSBbugaJpZM4JDse6
> .

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by yoyo1989** [comment]
done
